repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
    -   id: name-tests-test
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/MatthewRizzo/mattrizzo_devops
    rev: 1.2.2
    hooks:
    -   id: check-rust
        name: Check Rust
        description: Check Rust files for fmt and clippy errors
        entry: poetry run check-rust
        language: system
        stages: [push]
    -   id: mypy
        name: Python Typing - mypy
        description: Check Python files for typing errors with mypy
        entry: poetry run check-python-typing -p
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: markdown-linter
        name: markdown-linter
        entry: mdl -s .mdl_ruleset.rb
        language: ruby
        files: \.(md|mdown|markdown)$
        stages: [commit]
    -   id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          [
            "-rn",
            "-sn",
          ]
