repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: local
    hooks:
    - id: markdown-linter
      name: markdown-linter
      entry: mdl
      language: ruby
      files: \.(md|mdown|markdown)$
      stages: [commit]
