[package]
name = "tax_estimater"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "estimate-client"
path = "estimate-client/src/main.rs"

[lib]
name = "estimate_server"
path = "estimate-server/src/lib.rs"
